"""
SYBR API — Config generator service.

Generates a per-job run_sybr_config.yaml from the API submission parameters.
"""

from pathlib import Path

import yaml

from api.models import JobSubmitRequest


def generate_job_config(
    request: JobSubmitRequest,
    input_dir: Path,
    output_dir: Path,
) -> str:
    """
    Build a run_sybr_config.yaml string from API submission parameters.

    The generated config uses absolute paths for base_input_dir / base_output_dir
    so the pipeline resolves everything correctly regardless of working directory.
    """
    config = {
        # ── Base I/O directories ─────────────────────────────────────────
        "base_input_dir": str(input_dir),
        "base_output_dir": str(output_dir),

        # ── Pipeline stages ──────────────────────────────────────────────
        "run_stages": {
            # De-novo alignment flags: always false for API jobs (users upload
            # pre-computed Satsuma / LastZ files via the /upload endpoint).
            "run_satsuma_alignment": False,
            "run_lastz_alignment": False,
            "synteny_processing": request.run_stages.synteny_processing,
            "eba_analysis": request.run_stages.eba_analysis,
            "enrichment_analysis": request.run_stages.enrichment_analysis,
            "chainNet_generation": request.run_stages.chainNet_generation,
            "Ancestor_seq_recunstruction": request.run_stages.Ancestor_seq_recunstruction,
        },

        # ── Species / reference names ────────────────────────────────────
        "reference_name": request.reference_name,
        "reference_species": request.reference_species,

        # ── EBA parameters ───────────────────────────────────────────────
        "eba": {
            "n": request.eba.n,
            "r": request.eba.r,
            "p": request.eba.p,
        },

        # ── Enrichment ───────────────────────────────────────────────────
        "getenrich": {
            "r": request.getenrich.r,
        },
    }

    return yaml.dump(config, default_flow_style=False, sort_keys=False)


def write_job_config(
    request: JobSubmitRequest,
    job_dir: Path,
) -> Path:
    """
    Generate and write run_sybr_config.yaml into the job directory.

    Returns the path to the written config file.
    """
    input_dir = job_dir / "inputs"
    output_dir = job_dir / "outputs"

    config_content = generate_job_config(request, input_dir, output_dir)

    config_path = job_dir / "run_sybr_config.yaml"
    config_path.write_text(
        f"# Auto-generated by SYBR API — do not edit\n"
        f"# Job directory: {job_dir}\n\n"
        f"{config_content}"
    )

    return config_path
