[server]
# Max upload size per file in MB (default is 200)
maxUploadSize = 2048

# Max total message size in MB (for multiple files at once)
maxMessageSize = 2048

# Enable XSRF protection
enableXsrfProtection = true

[browser]
# Gather usage stats
gatherUsageStats = false
