# Streamlit Secrets Configuration
# This file should not be committed to version control (.gitignore it)

SYBR_API_URL = "http://192.168.25.76:8001/api/v1"
SYBR_API_KEY = "77ca33e84bf575ea708c620af2d2119be41eb1fea2d79f41"
ADMIN_PASSWORD = "Igib@4321"
